name: GrassBlockSMPPlugin
version: '${project.version}'
main: com.riverstone.unknown303.grassblocksmpplugin.GrassBlockSMPPlugin
api-version: '1.20'
authors: [Unknown_303YT, JoeyDee]
description: The Official Plugin of the GrassBlock SMP
commands:
  getLDHelm:
    description: Gives the player the Leader's Defence Helmet
    usage: /<command>
    permission: grassblocksmpplugin.getTeamItems
  getLDBoots:
      description: Gives the player the Leader's Defence Boots
      usage: /<command>
      permission: grassblocksmpplugin.getTeamItems
  getLDChestplate:
        description: Gives the player the Leader's Defence Chestplate
        usage: /<command>
        permission: grassblocksmpplugin.getTeamItems
  getLDLeggings:
    description: Gives the player the Leader's Defence Leggings
    usage: /<command>
    permission: grassblocksmpplugin.getTeamItems
  getLDSet:
    description: Gives the player a full set of Leader's Defence Armor
    usage: /<command>
    permission: grassblocksmpplugin.getTeamItems
  getLShield:
    description: Gives the player a Loner's Shield
    usage: /<command>
    permission: grassblocksmpplugin.getTeamItems
  withdraw:
    description: Withdraws the specified amount of lives
    usage: /<command>
    permission: grassblocksmpplugin.anyone
  toggle:
    description: Commands to toggle features of GrassBlockSMPPlugin
    usage: /<command>
    permission: grassblocksmpplugin.toggles
  frz:
    description: Freeze people
    usage: /<command>
    permission: grassblocksmpplugin.admin
  name:
    description: Set Custom Display Names
    usage: /<command>
    permission: grassblocksmpplugin.admin


permissions:
  grassblocksmpplugin.getTeamItems:
    description: Permissions for the Leader's Refuge Armor Set
    default: op
  grassblocksmpplugin.toggles:
    description: Permissions for toggling features
    default: op
  grassblocksmpplugin.anyone:
    description: Anyone permissions
    default: true
  grassblocksmpplugin.admin:
    description: Permissions for admins
    default: op

